In [0]:
import numpy as np

**Arrays and Lists**

In [0]:
# Python way
list_two = list(range(1, 4))
list_three = list(range(1, 4))
list_sum = []

for index in range(3):
  list_two[index] = list_two[index] ** 2
  list_three[index] = list_three[index] ** 3
  list_sum.append(list_two[index] + list_three[index])
print(list_sum)  

[2, 12, 36]


In [0]:
# Numpy way
array_two = np.arange(1, 4) ** 2
array_three = np.arange(1, 4) ** 3
print(array_two + array_three)

[ 2 12 36]


In [0]:
np.power(np.array([1, 2, 3]), 4)

array([ 1, 16, 81])

In [0]:
np.negative(np.array([1, 2, 3]))

array([-1, -2, -3])

In [0]:
np.exp(np.array([1, 2, 3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [0]:
np.log(np.array([1, 2, 3]))

array([0.        , 0.69314718, 1.09861229])

In [0]:
np.sin(np.array([1, 2, 3]))

array([0.84147098, 0.90929743, 0.14112001])

**Multidimesnional ararays**

In [0]:
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)

multi_array = np.array([x, y, z])
print(multi_array)
print(multi_array.shape)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
(3, 3)


In [0]:
w = np.linspace(1, 10, 50) # start, end, amount of samples between start and end
print(w)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [0]:
b = np.linspace(1, 30, 3, True) # False - end number is excluded
b

array([ 1. , 15.5, 30. ])

In [0]:
b = np.arange(1, 30)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [0]:
x = np.arange(3)
y = np.arange(3, 6)
z = np.arange(6, 9)

multi_array = np.array([x, y, z])
print(multi_array)
print(multi_array.shape)
multi_array[1, 2] # [n, m]
print(multi_array.dtype)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
int64


In [0]:
multi_array = np.array([x, y, z], dtype=np.int16)
print(multi_array.dtype)

int16


**1D Slicing**

In [0]:
x = np.arange(1, 10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [0]:
print(x[2:7])

[3 4 5 6 7]


In [0]:
print(x[2:7:2])

[3 5 7]


In [0]:
print(x[:7])

[1 2 3 4 5 6 7]


**Reshaping**

In [0]:
x = np.arange(9).reshape(3, 3) # (3, 5) -> error because we have 9 not 15 elements
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
x = np.arange(18).reshape(2, 3, 3) # (3, 3, 2)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


**Multidimensional slicing**

In [0]:
x = np.arange(18).reshape(3, 2, 3)
print(x)
print(x[1, 1, 1]) # imagine dimensions like towers

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [0]:
print(x[1, 0:2, 0:3]) # tower, range of rows, range of columns x[1, :2, :3]

[[ 6  7  8]
 [ 9 10 11]]


In [0]:
print(x[1, ...])

[[ 6  7  8]
 [ 9 10 11]]


In [0]:
print(x[:, 0, 0])

[ 0  6 12]


In [0]:
print(x[1, :2, :3:2]) # every second element in each row

[[ 6  8]
 [ 9 11]]


In [0]:
comparison_operation = x > 5
print(comparison_operation)
print(x[comparison_operation]) # x[x > 5]
print(x.max())
print(x.min())

[[[False False False]
  [False False False]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]]
[ 6  7  8  9 10 11 12 13 14 15 16 17]
17
0


**Manipulating array shapes**

In [0]:
x = np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
ravelled_array = x.ravel() # returns a view of the original array (affect original array)
ravelled_array[2] = 10000
print(ravelled_array)
print(x)

[    0     1 10000     3     4     5     6     7     8]
[[    0     1 10000]
 [    3     4     5]
 [    6     7     8]]


In [0]:
flattened_array = x.flatten() # returns a copy and allocates new memory
flattened_array[2] = 10000
print(flattened_array)
print(x)

[    0     1 10000     3     4     5     6     7     8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
y = np.arange(9)
y.shape = [3, 3]
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
print(y.transpose()) # y.T

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [0]:
print(np.resize(y, (6, 6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [0]:
print(np.zeros((6,), dtype=int))

[0 0 0 0 0 0]


In [0]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [0]:
print(np.ones((2, 3), dtype=int))

[[1 1 1]
 [1 1 1]]


In [0]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [0]:
print(np.random.rand(4, 4)) # 0 - 1

[[0.5106284  0.20979511 0.8726291  0.49361134]
 [0.95899509 0.54983046 0.73743965 0.28403544]
 [0.24164064 0.29557322 0.71793774 0.99418372]
 [0.39200658 0.33322016 0.733547   0.39936663]]


**Matrix multiplication**

In [0]:
mat_a = np.matrix([0, 3, 5, 5, 5, 2]).reshape(2, 3)
mat_a

matrix([[0, 3, 5],
        [5, 5, 2]])

In [0]:
mat_b = np.matrix([3, 4, 3, -2, 4, -2]).reshape(3, 2)
mat_b

matrix([[ 3,  4],
        [ 3, -2],
        [ 4, -2]])

In [0]:
mat_a * mat_b # same result with np.array

matrix([[ 29, -16],
        [ 38,   6]])

In [0]:
product = np.matmul(mat_a, mat_b) # same result with np.array
product

matrix([[ 29, -16],
        [ 38,   6]])

In [0]:
mat_a @ mat_b

matrix([[ 29, -16],
        [ 38,   6]])

**Stacking**

In [0]:
x = np.arange(4).reshape(2, 2)
print(x)

[[0 1]
 [2 3]]


In [0]:
y = np.arange(4, 8).reshape(2, 2)
print(y)

[[4 5]
 [6 7]]


In [0]:
z = np.hstack((x, y)) # horizontal stacking (with same shape[0])
print(z)

[[0 1 4 5]
 [2 3 6 7]]


In [0]:
x = np.arange(4).reshape(2, 2)
print(x)

[[0 1]
 [2 3]]


In [0]:
y = np.arange(8).reshape(4, 2)
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [0]:
z = np.vstack((x, y)) # vertical stacking (with same shape[1])
print(z)

[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]


In [0]:
w = np.concatenate((x, y), axis=0) # axis=1 -> error
print(w)

[[0 1]
 [2 3]
 [0 1]
 [2 3]
 [4 5]
 [6 7]]


In [0]:
x = np.arange(4).reshape(2, 2)
y = x*2
print(y)

[[0 2]
 [4 6]]


In [0]:
depth_stack = np.dstack((x, y)) # we added 3rd dimension
print(depth_stack)
print(depth_stack.shape)

[[[0 0]
  [1 2]]

 [[2 4]
  [3 6]]]
(2, 2, 2)


In [0]:
x = np.arange(4).reshape(2, 2)
y = x*2
print(y)

[[0 2]
 [4 6]]


In [0]:
print(np.column_stack((x, y)))

[[0 1 0 2]
 [2 3 4 6]]


In [0]:
print(np.column_stack((x, y)) == np.hstack((x, y)))

[[ True  True  True  True]
 [ True  True  True  True]]


In [0]:
x = np.arange(4)
y = x*2
print(np.column_stack((x, y)))

[[0 0]
 [1 2]
 [2 4]
 [3 6]]


In [0]:
print(np.hstack((x, y)))

[0 1 2 3 0 2 4 6]


In [0]:
x = np.arange(4).reshape(2, 2)
y = x*2
print(np.row_stack((x, y)))

[[0 1]
 [2 3]
 [0 2]
 [4 6]]


In [0]:
print(np.row_stack((x, y)) == np.vstack((x, y)))

[[ True  True]
 [ True  True]
 [ True  True]
 [ True  True]]
