In [0]:
from __future__ import print_function
import torch
import numpy as np

In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[8.6509e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [3.2871e+21, 1.0432e+21, 3.2770e-09],
        [1.6853e+22, 3.4332e-06, 5.4663e+22],
        [4.2484e-05, 5.3129e-08, 5.0948e-14]])


In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6780, 0.4452, 0.6599],
        [0.9402, 0.5733, 0.5576],
        [0.6264, 0.0181, 0.4673],
        [0.1059, 0.1337, 0.2504],
        [0.6230, 0.4840, 0.9361]])


In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
x = torch.tensor([23, 0.2])
print(x)

tensor([23.0000,  0.2000])


In [0]:
x = torch.ones(5, 5, dtype=torch.double)
new_x = torch.randn_like(x, dtype=torch.double)
print(x)
print(new_x)
print(x.size())

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[-1.4323,  0.8244,  0.0683, -2.4623, -0.8888],
        [ 0.2236, -1.1728,  1.4209,  0.3550,  0.7139],
        [ 0.0782, -0.5726, -1.0972, -0.7044, -1.2957],
        [-0.2818, -0.9042,  0.5134,  0.9007,  0.8180],
        [ 0.9679, -2.0548, -0.8333,  0.1178, -1.6840]], dtype=torch.float64)
torch.Size([5, 5])


In [0]:
y = torch.rand(5, 5)
print(y)

tensor([[0.1750, 0.3612, 0.7521, 0.3048, 0.5725],
        [0.6291, 0.9850, 0.4813, 0.7829, 0.2854],
        [0.6245, 0.1175, 0.8025, 0.6705, 0.9874],
        [0.9030, 0.2520, 0.3672, 0.3303, 0.3417],
        [0.0697, 0.5072, 0.9346, 0.1181, 0.1441]])


In [0]:
z = new_x + y
print(z)

tensor([[-1.2573,  1.1856,  0.8204, -2.1575, -0.3163],
        [ 0.8527, -0.1878,  1.9022,  1.1380,  0.9993],
        [ 0.7027, -0.4551, -0.2948, -0.0339, -0.3083],
        [ 0.6211, -0.6522,  0.8807,  1.2309,  1.1596],
        [ 1.0376, -1.5475,  0.1013,  0.2359, -1.5399]], dtype=torch.float64)


In [0]:
z = torch.add(new_x, y)
print(z)

tensor([[-1.2573,  1.1856,  0.8204, -2.1575, -0.3163],
        [ 0.8527, -0.1878,  1.9022,  1.1380,  0.9993],
        [ 0.7027, -0.4551, -0.2948, -0.0339, -0.3083],
        [ 0.6211, -0.6522,  0.8807,  1.2309,  1.1596],
        [ 1.0376, -1.5475,  0.1013,  0.2359, -1.5399]], dtype=torch.float64)


In [0]:
result = torch.zeros(5, 5)
torch.add(new_x, y, out=result)
print(result)

tensor([[-1.2573,  1.1856,  0.8204, -2.1575, -0.3163],
        [ 0.8527, -0.1878,  1.9022,  1.1380,  0.9993],
        [ 0.7027, -0.4551, -0.2948, -0.0339, -0.3083],
        [ 0.6211, -0.6522,  0.8807,  1.2309,  1.1596],
        [ 1.0376, -1.5475,  0.1013,  0.2359, -1.5399]])


In [0]:
z = new_x.add_(y) # Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x
print(z)

tensor([[-0.0324,  3.7139,  6.0848, -0.0239,  3.6912],
        [ 5.2564,  6.7071,  5.2715,  6.6186,  2.9970],
        [ 5.0744,  0.3671,  5.3224,  4.6597,  6.6034],
        [ 6.9419,  1.1117,  3.4514,  3.5429,  3.5512],
        [ 1.5258,  2.0032,  6.6435,  1.0629, -0.5310]], dtype=torch.float64)


In [0]:
print(z)
print(z[:, 1])

tensor([[-0.0324,  3.7139,  6.0848, -0.0239,  3.6912],
        [ 5.2564,  6.7071,  5.2715,  6.6186,  2.9970],
        [ 5.0744,  0.3671,  5.3224,  4.6597,  6.6034],
        [ 6.9419,  1.1117,  3.4514,  3.5429,  3.5512],
        [ 1.5258,  2.0032,  6.6435,  1.0629, -0.5310]], dtype=torch.float64)
tensor([3.7139, 6.7071, 0.3671, 1.1117, 2.0032], dtype=torch.float64)


In [0]:
# Resizing

x = torch.rand(5, 10)
y = x.view(50)
z = y.view(-1, 5)
print(x, x.size())
print(y, y.size())
print(z, z.size())

tensor([[0.9745, 0.0969, 0.0011, 0.3037, 0.8847, 0.6630, 0.7960, 0.5647, 0.0935,
         0.6508],
        [0.1278, 0.0907, 0.0285, 0.4513, 0.6877, 0.7985, 0.9659, 0.9669, 0.0862,
         0.9082],
        [0.7119, 0.3539, 0.5781, 0.3203, 0.7330, 0.5703, 0.4610, 0.6580, 0.0683,
         0.9140],
        [0.5042, 0.5872, 0.6981, 0.6604, 0.3612, 0.4727, 0.8910, 0.1055, 0.7018,
         0.3327],
        [0.9556, 0.6366, 0.5753, 0.1341, 0.4373, 0.8265, 0.6931, 0.4221, 0.8277,
         0.9298]]) torch.Size([5, 10])
tensor([0.9745, 0.0969, 0.0011, 0.3037, 0.8847, 0.6630, 0.7960, 0.5647, 0.0935,
        0.6508, 0.1278, 0.0907, 0.0285, 0.4513, 0.6877, 0.7985, 0.9659, 0.9669,
        0.0862, 0.9082, 0.7119, 0.3539, 0.5781, 0.3203, 0.7330, 0.5703, 0.4610,
        0.6580, 0.0683, 0.9140, 0.5042, 0.5872, 0.6981, 0.6604, 0.3612, 0.4727,
        0.8910, 0.1055, 0.7018, 0.3327, 0.9556, 0.6366, 0.5753, 0.1341, 0.4373,
        0.8265, 0.6931, 0.4221, 0.8277, 0.9298]) torch.Size([50])
tensor([[0.9745, 0

In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.6110])
-1.6110203266143799


In [0]:
a = torch.ones(5, 5)
print(a)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [0]:
b = a.numpy()
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [0]:
c = a + b # numpy array become  tensor
print(c)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])


In [0]:
b_t = torch.from_numpy(b)
print(b_t)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [0]:
torch.cuda.is_available()

True

In [0]:
device = torch.device('cuda')
y = y.to(device)
print(y)

tensor([0.9745, 0.0969, 0.0011, 0.3037, 0.8847, 0.6630, 0.7960, 0.5647, 0.0935,
        0.6508, 0.1278, 0.0907, 0.0285, 0.4513, 0.6877, 0.7985, 0.9659, 0.9669,
        0.0862, 0.9082, 0.7119, 0.3539, 0.5781, 0.3203, 0.7330, 0.5703, 0.4610,
        0.6580, 0.0683, 0.9140, 0.5042, 0.5872, 0.6981, 0.6604, 0.3612, 0.4727,
        0.8910, 0.1055, 0.7018, 0.3327, 0.9556, 0.6366, 0.5753, 0.1341, 0.4373,
        0.8265, 0.6931, 0.4221, 0.8277, 0.9298], device='cuda:0')
